// https://www.ctan.org/tex-archive/fonts/lm/
export const lmdb = {
  'latinmodern-math': new URL('./fonts/lm/latinmodern-math.otf', import.meta.url),
  'lmmono10-italic': new URL('./fonts/lm/lmmono10-italic.otf', import.meta.url),
  'lmmono10-regular': new URL('./fonts/lm/lmmono10-regular.otf', import.meta.url),
  'lmmono12-regular': new URL('./fonts/lm/lmmono12-regular.otf', import.meta.url),
  'lmmono8-regular': new URL('./fonts/lm/lmmono8-regular.otf', import.meta.url),
  'lmmono9-regular': new URL('./fonts/lm/lmmono9-regular.otf', import.meta.url),
  'lmmonocaps10-oblique': new URL('./fonts/lm/lmmonocaps10-oblique.otf',import.meta.url),
  'lmmonocaps10-regular': new URL('./fonts/lm/lmmonocaps10-regular.otf',import.meta.url),
  'lmmonolt10-bold': new URL('./fonts/lm/lmmonolt10-bold.otf', import.meta.url),
  'lmmonolt10-boldoblique': new URL('./fonts/lm/lmmonolt10-boldoblique.otf',import.meta.url),
  'lmmonolt10-oblique': new URL('./fonts/lm/lmmonolt10-oblique.otf', import.meta.url),
  'lmmonolt10-regular': new URL('./fonts/lm/lmmonolt10-regular.otf', import.meta.url),
  'lmmonoltcond10-oblique': new URL('./fonts/lm/lmmonoltcond10-oblique.otf',import.meta.url),
  'lmmonoltcond10-regular': new URL('./fonts/lm/lmmonoltcond10-regular.otf',import.meta.url),
  'lmmonoprop10-oblique': new URL('./fonts/lm/lmmonoprop10-oblique.otf',import.meta.url),
  'lmmonoprop10-regular': new URL('./fonts/lm/lmmonoprop10-regular.otf',import.meta.url),
  'lmmonoproplt10-bold': new URL('./fonts/lm/lmmonoproplt10-bold.otf',import.meta.url),
  'lmmonoproplt10-boldoblique': new URL('./fonts/lm/lmmonoproplt10-boldoblique.otf',import.meta.url),
  'lmmonoproplt10-oblique': new URL('./fonts/lm/lmmonoproplt10-oblique.otf',import.meta.url),
  'lmmonoproplt10-regular': new URL('./fonts/lm/lmmonoproplt10-regular.otf',import.meta.url),
  'lmmonoslant10-regular': new URL('./fonts/lm/lmmonoslant10-regular.otf',import.meta.url),
  'lmroman10-bold': new URL('./fonts/lm/lmroman10-bold.otf', import.meta.url),
  'lmroman10-bolditalic': new URL('./fonts/lm/lmroman10-bolditalic.otf',import.meta.url),
  'lmroman10-italic': new URL('./fonts/lm/lmroman10-italic.otf', import.meta.url),
  'lmroman10-regular': new URL('./fonts/lm/lmroman10-regular.otf', import.meta.url),
  'lmroman12-bold': new URL('./fonts/lm/lmroman12-bold.otf', import.meta.url),
  'lmroman12-italic': new URL('./fonts/lm/lmroman12-italic.otf', import.meta.url),
  'lmroman12-regular': new URL('./fonts/lm/lmroman12-regular.otf', import.meta.url),
  'lmroman17-regular': new URL('./fonts/lm/lmroman17-regular.otf', import.meta.url),
  'lmroman5-bold': new URL('./fonts/lm/lmroman5-bold.otf', import.meta.url),
  'lmroman5-regular': new URL('./fonts/lm/lmroman5-regular.otf', import.meta.url),
  'lmroman6-bold': new URL('./fonts/lm/lmroman6-bold.otf', import.meta.url),
  'lmroman6-regular': new URL('./fonts/lm/lmroman6-regular.otf', import.meta.url),
  'lmroman7-bold': new URL('./fonts/lm/lmroman7-bold.otf', import.meta.url),
  'lmroman7-italic': new URL('./fonts/lm/lmroman7-italic.otf', import.meta.url),
  'lmroman7-regular': new URL('./fonts/lm/lmroman7-regular.otf', import.meta.url),
  'lmroman8-bold': new URL('./fonts/lm/lmroman8-bold.otf', import.meta.url),
  'lmroman8-italic': new URL('./fonts/lm/lmroman8-italic.otf', import.meta.url),
  'lmroman8-regular': new URL('./fonts/lm/lmroman8-regular.otf', import.meta.url),
  'lmroman9-bold': new URL('./fonts/lm/lmroman9-bold.otf', import.meta.url),
  'lmroman9-italic': new URL('./fonts/lm/lmroman9-italic.otf', import.meta.url),
  'lmroman9-regular': new URL('./fonts/lm/lmroman9-regular.otf', import.meta.url),
  'lmromancaps10-oblique': new URL('./fonts/lm/lmromancaps10-oblique.otf',import.meta.url),
  'lmromancaps10-regular': new URL('./fonts/lm/lmromancaps10-regular.otf',import.meta.url),
  'lmromandemi10-oblique': new URL('./fonts/lm/lmromandemi10-oblique.otf',import.meta.url),
  'lmromandemi10-regular': new URL('./fonts/lm/lmromandemi10-regular.otf',import.meta.url),
  'lmromandunh10-oblique': new URL('./fonts/lm/lmromandunh10-oblique.otf',import.meta.url),
  'lmromandunh10-regular': new URL('./fonts/lm/lmromandunh10-regular.otf',import.meta.url),
  'lmromanslant10-bold': new URL('./fonts/lm/lmromanslant10-bold.otf',import.meta.url),
  'lmromanslant10-regular': new URL('./fonts/lm/lmromanslant10-regular.otf',import.meta.url),
  'lmromanslant12-regular': new URL('./fonts/lm/lmromanslant12-regular.otf',import.meta.url),
  'lmromanslant17-regular': new URL('./fonts/lm/lmromanslant17-regular.otf',import.meta.url),
  'lmromanslant8-regular': new URL('./fonts/lm/lmromanslant8-regular.otf',import.meta.url),
  'lmromanslant9-regular': new URL('./fonts/lm/lmromanslant9-regular.otf',import.meta.url),
  'lmromanunsl10-regular': new URL('./fonts/lm/lmromanunsl10-regular.otf',import.meta.url),
  'lmsans10-bold': new URL('./fonts/lm/lmsans10-bold.otf', import.meta.url),
  'lmsans10-boldoblique': new URL('./fonts/lm/lmsans10-boldoblique.otf'import.meta.url),
  'lmsans10-oblique': new URL('./fonts/lm/lmsans10-oblique.otf', import.meta.url),
  'lmsans10-regular': new URL('./fonts/lm/lmsans10-regular.otf', import.meta.url),
  'lmsans12-oblique': new URL('./fonts/lm/lmsans12-oblique.otf', import.meta.url),
  'lmsans12-regular': new URL('./fonts/lm/lmsans12-regular.otf', import.meta.url),
  'lmsans17-oblique': new URL('./fonts/lm/lmsans17-oblique.otf', import.meta.url),
  'lmsans17-regular': new URL('./fonts/lm/lmsans17-regular.otf', import.meta.url),
  'lmsans8-oblique': new URL('./fonts/lm/lmsans8-oblique.otf', import.meta.url),
  'lmsans8-regular': new URL('./fonts/lm/lmsans8-regular.otf', import.meta.url),
  'lmsans9-oblique': new URL('./fonts/lm/lmsans9-oblique.otf', import.meta.url),
  'lmsans9-regular': new URL('./fonts/lm/lmsans9-regular.otf', import.meta.url),
  'lmsansdemicond10-oblique': new URL('./fonts/lm/lmsansdemicond10-oblique.otf'import.meta.url),
  'lmsansdemicond10-regular': new URL('./fonts/lm/lmsansdemicond10-regular.otf'import.meta.url),
  'lmsansquot8-bold': new URL('./fonts/lm/lmsansquot8-bold.otf', import.meta.url),
  'lmsansquot8-boldoblique': new URL('./fonts/lm/lmsansquot8-boldoblique.otf'import.meta.url),
  'lmsansquot8-oblique': new URL('./fonts/lm/lmsansquot8-oblique.otf'import.meta.url),
  'lmsansquot8-regular': new URL('./fonts/lm/lmsansquot8-regular.otf'import.meta.url),
}

export const technika = [
  {
    src: new URL('./Technika-Bold.otf', import.meta.url).toString(),
    fontWeight: 'bold',
  },
  {
    src: new URL('./Technika-BoldItalic.otf', import.meta.url).toString(),
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  {
    src: new URL('./Technika-Book.otf', import.meta.url).toString(),
    fontWeight: 'light',
  },
  {
    src: new URL('./Technika-BookItalic.otf', import.meta.url).toString(),
    fontWeight: 'light',
    fontStyle: 'italic',
  },
  {
    src: new URL('./Technika-Italic.otf', import.meta.url).toString(),
    fontStyle: 'italic',
  },
  {
    src: new URL('./Technika-Regular.otf', import.meta.url).toString(),
  },
]
