[package]
name = "netvr_data"
version = "0.1.0"
edition = "2021"


[dependencies]
bincode = "1.3.3"
serde = "1.0.159"
thiserror = "1.0.40"
nalgebra = { version = "0.32.2", features = ["serde"] }
chrono = {version = "0.4.24", default-features = false, features = ["serde"]}

[build-dependencies]
serde = "1.0.159"
serde-reflection = "0.3.6"
openxr-sys = "0.9.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openxr-sys = "0.9.3"
quinn = "0.9.3"
tokio = { version = "1.27.0", features = ["net", "time", "macros"] }
