[package]
name = "netvr_data"
version = "0.1.0"
edition = "2021"


[dependencies]
bincode = "1.3.3"
openxr-sys = "0.9.3"
serde = "1.0.159"

[build-dependencies]
serde = "1.0.159"
serde-reflection = "0.3.6"
openxr-sys = "0.9.3"
