[workspace]

members = [
    "xr_layer",
    "isbl_netvr_rust"
]

[patch.crates-io]
openxr-sys = { git = "https://github.com/Ralith/openxrs", commit = "05a0f442d93e627bf45b341100ad09c621d6ab06" }
openxr = { git = "https://github.com/Ralith/openxrs", commit = "05a0f442d93e627bf45b341100ad09c621d6ab06" }
