name = "netvr"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-19"
account_id = "cce7f3b93d1cc5016fffc6068a30a3bb"

[build]
command = "npm run build"
[build.upload]
format = "modules"
dir = "dist"
main = "worker.mjs"

[site]
bucket = "../netvr-dashboard/dist"

[durable_objects]
bindings = [
  { name = "WEBSOCKET", class_name = "DurableObjectWebSocket" }
]

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectWebSocket"]
