[target.aarch64-linux-android]
linker="D:\\Stuff\\UnityEditors\\2021.2.16f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\NDK\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android21-clang++.cmd"
