[package]
name = "xr_layer"
version = "0.1.0"
authors = ["Isabella Skořepová"]
edition = "2021"
links = "isbl_xr_layer"

[dependencies]
openxr = "0.17.1"
openxr-sys = "0.9.3"
lazy_static = "1.4.0"
once_cell = "1.12.0"
