[package]
name = "netvr_plugin"
version = "0.1.0"
edition = "2021"

[lib]
name = "netvr_plugin"
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = "1.4.0"
xr_layer = { path = "../xr_layer" }
tracing-chrome = { git = "https://github.com/CodeWitchBella/tracing-chrome.git", rev = "6f41686f89971d331542b39d91b4755b6a2ccbc5" }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde-reflection = "0.3.6"
netvr_data = { path = "../netvr_data" }
netvr_client = { path = "../netvr_client" }
tokio = { version = "1.27.0", features = ["rt"] }
tokio-util = { version = "0.7.7" }
anyhow = "1.0.70"
thiserror = "1.0.40"
quinn = "0.9.3"
serde = "1.0.159"
