/* eslint-disable */
// prettier-ignore
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(Module = {})  {

var c;c||(c=typeof Module !== 'undefined' ? Module : {});var p,q;c.ready=new Promise(function(a,b){p=a;q=b});var u=Object.assign({},c),v="";"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src);_scriptDir&&(v=_scriptDir);0!==v.indexOf("blob:")?v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):v="";var x=console.warn.bind(console);Object.assign(c,u);u=null;"object"!=typeof WebAssembly&&y("no native wasm support detected");
var z,A=!1,B="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b){if(a){var e=D,d=a+b;for(b=a;e[b]&&!(b>=d);)++b;if(16<b-a&&e.buffer&&B)a=B.decode(e.subarray(a,b));else{for(d="";a<b;){var f=e[a++];if(f&128){var g=e[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=e[a++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|e[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}var E,D,F,G,I,J,K;
function L(){var a=z.buffer;c.HEAP8=E=new Int8Array(a);c.HEAP16=F=new Int16Array(a);c.HEAP32=G=new Int32Array(a);c.HEAPU8=D=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAPU32=I=new Uint32Array(a);c.HEAPF32=J=new Float32Array(a);c.HEAPF64=K=new Float64Array(a)}var M,aa=[],O=[],ba=[],P=0,Q=null,R=null;function y(a){a="Aborted("+a+")";x(a);A=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");q(a);throw a;}
function S(a){return a.startsWith("data:application/octet-stream;base64,")}var T;c.locateFile?(T="cpp_netvr.wasm",S(T)||(T=v+T)):T=(new URL("cpp_netvr.wasm",import.meta.url)).href;function U(){try{throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}
function ca(a){return"function"==typeof fetch?fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return U()}):Promise.resolve().then(function(){return U()})}function da(a,b,e){return ca(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(e,function(d){x("failed to asynchronously prepare wasm: "+d);y(d)})}
function ea(a,b){var e=T;return"function"!=typeof WebAssembly.instantiateStreaming||S(e)||"function"!=typeof fetch?da(e,a,b):fetch(e,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(f){x("wasm streaming compile failed: "+f);x("falling back to ArrayBuffer instantiation");return da(e,a,b)})})}function V(a){for(;0<a.length;)a.shift()(c)}
function fa(a){this.u=a-24;this.F=function(b){I[this.u+4>>2]=b};this.B=function(b){I[this.u+8>>2]=b};this.C=function(){G[this.u>>2]=0};this.A=function(){E[this.u+12>>0]=0};this.D=function(){E[this.u+13>>0]=0};this.G=function(b,e){this.v();this.F(b);this.B(e);this.C();this.A();this.D()};this.v=function(){I[this.u+16>>2]=0}}var ha=0;
function ia(a,b,e,d){var f={string:l=>{var w=0;if(null!==l&&void 0!==l&&0!==l){var r=(l.length<<2)+1;w=W(r);var n=w,t=D;if(0<r){r=n+r-1;for(var H=0;H<l.length;++H){var m=l.charCodeAt(H);if(55296<=m&&57343>=m){var na=l.charCodeAt(++H);m=65536+((m&1023)<<10)|na&1023}if(127>=m){if(n>=r)break;t[n++]=m}else{if(2047>=m){if(n+1>=r)break;t[n++]=192|m>>6}else{if(65535>=m){if(n+2>=r)break;t[n++]=224|m>>12}else{if(n+3>=r)break;t[n++]=240|m>>18;t[n++]=128|m>>12&63}t[n++]=128|m>>6&63}t[n++]=128|m&63}}t[n]=0}}return w},
array:l=>{var w=W(l.length);E.set(l,w);return w}};a=c["_"+a];var g=[],h=0;if(d)for(var k=0;k<d.length;k++){var N=f[e[k]];N?(0===h&&(h=ja()),g[k]=N(d[k])):g[k]=d[k]}e=a.apply(null,g);return e=function(l){0!==h&&ka(h);return"string"===b?C(l):"boolean"===b?!!l:l}(e)}
var X=[],Y=void 0,la=[],ma={a:function(a,b,e){(new fa(a)).G(b,e);ha++;throw a;},b:function(){y("")},d:function(a,b,e){D.copyWithin(a,b,b+e)},c:function(a){var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var e=1;4>=e;e*=2){var d=b*(1+.2/e);d=Math.min(d,a+100663296);var f=Math,g=f.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var h=z.buffer;try{z.grow(g.call(f,2147483648,d)-h.byteLength+65535>>>16);L();var k=1;break a}catch(N){}k=void 0}if(k)return!0}return!1}};
(function(){var a={a:ma};P++;ea(a,function(b){c.asm=b.instance.exports;z=c.asm.e;L();M=c.asm.l;O.unshift(c.asm.f);P--;0==P&&(null!==Q&&(clearInterval(Q),Q=null),R&&(b=R,R=null,b()))}).catch(q);return{}})();c._isbl_netvr_hook_get_instance_proc_addr=function(){return(c._isbl_netvr_hook_get_instance_proc_addr=c.asm.g).apply(null,arguments)};c._isbl_netvr_on_system_change=function(){return(c._isbl_netvr_on_system_change=c.asm.h).apply(null,arguments)};
c._free=function(){return(c._free=c.asm.i).apply(null,arguments)};c._isbl_netvr_set_logger=function(){return(c._isbl_netvr_set_logger=c.asm.j).apply(null,arguments)};c._malloc=function(){return(c._malloc=c.asm.k).apply(null,arguments)};c._isbl_netvr_calibration_create=function(){return(c._isbl_netvr_calibration_create=c.asm.m).apply(null,arguments)};c._isbl_netvr_calibration_destroy=function(){return(c._isbl_netvr_calibration_destroy=c.asm.n).apply(null,arguments)};
c._isbl_netvr_calibration_add_pair=function(){return(c._isbl_netvr_calibration_add_pair=c.asm.o).apply(null,arguments)};c._isbl_netvr_calibration_compute=function(){return(c._isbl_netvr_calibration_compute=c.asm.p).apply(null,arguments)};function ja(){return(ja=c.asm.q).apply(null,arguments)}function ka(){return(ka=c.asm.r).apply(null,arguments)}function W(){return(W=c.asm.s).apply(null,arguments)}c.UTF8ToString=C;
c.cwrap=function(a,b,e,d){var f=!e||e.every(g=>"number"===g||"boolean"===g);return"string"!==b&&f&&!d?c["_"+a]:function(){return ia(a,b,e,arguments)}};
c.addFunction=function(a,b){if(!Y){Y=new WeakMap;var e=M.length;if(Y)for(var d=0;d<0+e;d++){var f=d;var g=X[f];g||(f>=X.length&&(X.length=f+1),X[f]=g=M.get(f));(f=g)&&Y.set(f,d)}}if(e=Y.get(a)||0)return e;if(la.length)e=la.pop();else{try{M.grow(1)}catch(k){if(!(k instanceof RangeError))throw k;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}e=M.length-1}try{d=e,M.set(d,a),X[d]=M.get(d)}catch(k){if(!(k instanceof TypeError))throw k;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;
f={i:"i32",j:"i32",f:"f32",d:"f64",p:"i32"};g={parameters:[],results:"v"==b[0]?[]:[f[b[0]]]};for(var h=1;h<b.length;++h)g.parameters.push(f[b[h]]),"j"===b[h]&&g.parameters.push("i32");b=new d(g,a)}else{d=[1];f=b.slice(0,1);b=b.slice(1);g={i:127,p:127,j:126,f:125,d:124};d.push(96);h=b.length;128>h?d.push(h):d.push(h%128|128,h>>7);for(h=0;h<b.length;++h)d.push(g[b[h]]);"v"==f?d.push(0):d.push(1,g[f]);b=[0,97,115,109,1,0,0,0,1];f=d.length;128>f?b.push(f):b.push(f%128|128,f>>7);b.push.apply(b,d);b.push(2,
7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}d=e;M.set(d,b);X[d]=M.get(d)}Y.set(a,e);return e};c.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return E[a>>0];case "i8":return E[a>>0];case "i16":return F[a>>1];case "i32":return G[a>>2];case "i64":return G[a>>2];case "float":return J[a>>2];case "double":return K[a>>3];case "*":return I[a>>2];default:y("invalid type for getValue: "+b)}};
var Z;R=function oa(){Z||pa();Z||(R=oa)};function pa(){0<P||(V(aa),0<P||Z||(Z=!0,c.calledRun=!0,A||(V(O),p(c),V(ba))))}pa();


  return Module.ready
}

);
})();
export default Module
