[package]
name = "isbl_netvr_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "isbl_netvr_rust"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
xr_layer = { path = "../xr_layer" }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-opentelemetry = { version = "0.17.4" }
opentelemetry-jaeger = { version = "0.16.0", features = [
	"reqwest_blocking_collector_client",
] }
