[package]
name = "isbl_netvr_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "isbl_netvr_rust"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
xr_layer = { path = "../xr_layer" }
