name: netvr-unity
on: [push]
jobs:
    build:
        name: Build netvr-unity ✨
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  lfs: true
            - uses: actions/cache@v2
              with:
                  path: netvr-unity/Library
                  key: Library-${{ hashFiles('netvr-unity/Assets/**', 'netvr-unity/Packages/**', 'netvr-unity/ProjectSettings/**') }}
                  restore-keys: |
                      Library-

            - name: Download dynamic library
              uses: dawidd6/action-download-artifact@v2
              with:
                  github_token: ${{secrets.GITHUB_TOKEN}}
                  workflow: netvr-cpp.yaml
                  workflow_conclusion: success
                  commit: ${{github.sha}}
                  name: Plugins
                  path: netvr-unity/Assets/Plugins

            - name: Build project
              uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  targetPlatform: StandaloneWindows
                  projectPath: netvr-unity
                  versioning: Semantic

            - uses: actions/upload-artifact@v2
              with:
                  name: Build
                  path: build
